version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: beatsai-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: beatsai
      POSTGRES_PASSWORD: beatsai
      POSTGRES_DB: beatsai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beatsai"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 